/*
 * SpecJson
 *
 * This file was automatically generated by Qordoba.com v2.0  on 11/30/2016
 */
package com.qordoba.developers.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class Language 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5029584430452812704L;
    private int id;
    private List<User> users;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("users")
    public List<User> getUsers ( ) { 
        return this.users;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("users")
    public void setUsers (List<User> value) { 
        this.users = value;
    }
 
}
 