/*
 * SpecJson
 *
 * This file was automatically generated by Qordoba.com v2.0  on 11/30/2016
 */
package com.qordoba.developers.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class MilestoneLanguage 
        implements java.io.Serializable {
    private static final long serialVersionUID = 4783297088320252323L;
    private List<Language> languages;
    private Milestone milestone;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("languages")
    public List<Language> getLanguages ( ) { 
        return this.languages;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("languages")
    public void setLanguages (List<Language> value) { 
        this.languages = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("milestone")
    public Milestone getMilestone ( ) { 
        return this.milestone;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("milestone")
    public void setMilestone (Milestone value) { 
        this.milestone = value;
    }
 
}
 