/*
 * SpecJson
 *
 * This file was automatically generated by Qordoba.com on 11/30/2016
 */
package com.qordoba.developers.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class StringFile 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5049532472200786340L;
    private String fileName;
    private String fileType;
    private String id;
    private List<Integer> sourceColumns;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("file_name")
    public String getFileName ( ) { 
        return this.fileName;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("file_name")
    public void setFileName (String value) { 
        this.fileName = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("file_type")
    public String getFileType ( ) { 
        return this.fileType;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("file_type")
    public void setFileType (String value) { 
        this.fileType = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("source_columns")
    public List<Integer> getSourceColumns ( ) { 
        return this.sourceColumns;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("source_columns")
    public void setSourceColumns (List<Integer> value) { 
        this.sourceColumns = value;
    }
 
}
 