/*
 * SpecJson
 *
 * This file was automatically generated by Qordoba.com on 11/30/2016
 */
package com.qordoba.developers.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class User 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5477511300538938064L;
    private int id;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public int getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (int value) { 
        this.id = value;
    }
 
}
 